### ISSUE TITLE
Email Attribute Validation Not working on View Profile Section.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2054] opened 2021-03-15 11:48 UTC
## Describe the issue
Email Attribute Validation/RegEx  not working   with email field on View Profile section.

## Steps To Reproduce
Steps to reproduce the behaviour:
 1. Go to Admin UI 
 2. Go to user
 3. Add New user
 4. Login with user credential.
 4. Try to update user's email with blank value or try with different pattern (eg. test123 or 1234)
 

 
## Expected behaviour
  The user should not updated without validating email with proper pattern.

## Actual behavior
 The user can update the profile without validation. 

.

## Desktop (please complete the following information):
 - OS:  ubuntu 20.04
 - Gluu version : 4.2.3

**Comment by cstpraveen** [comment] 2021-05-25 10:21
May I know why this is updated as Low Priority? It is major issue right?

**Comment by MohitMaliFtechiz** [comment] 2022-04-05 13:14
this issue has been tested, In 4.4.0 beta i am still able to produce this.  On updatePerson form validation is working but on viewprofile form validation is still not working.

**Comment by shekhar16** [comment] 2022-04-07 19:57
https://github.com/GluuFederation/oxTrust/pull/2144

**Comment by shekhar16** [comment] 2022-04-07 19:58
added validation for email on view profile page. Here is the screenshot.
![image](https://user-images.githubusercontent.com/15937500/162286007-a2a47981-0870-4bfa-a726-85d044b844bc.png)

**Comment by MohitMaliFtechiz** [comment] 2022-04-11 05:56
this issue has been fixed, however  the email validation error message Should not be like ``` Please provide a valid email address ``` it needs to be like ``` Validation Error: Value not according to pattern '[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]' ``` .

**Comment by yurem** [comment] 2022-04-12 08:36
@MohitMaliFtechiz Why do you think we need to show user regular expression in error message?

**Comment by yurem** [comment] 2022-04-12 08:37
Here is same issue: https://github.com/GluuFederation/oxTrust/issues/2076

**Comment by shekhar16** [comment] 2022-04-15 16:39
@MohitMaliFtechiz  I think the issue is fixed and closing this ticket. Please let us know if anything found.

**Closed by shekhar16** 2022-04-15 16:39 UTC
Labels: bug
