### ISSUE TITLE
Unable to upload favicon/logo through oxtrust

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1997] opened 2020-07-08 09:43 UTC
## Describe the issue
Unable to upload favicon/logo through oxtrust

## Steps To Reproduce
1. login to gluu-server.
2. Go to ' Configuration > Organization configuration > Organization setting. '
3. Upload logo file.

## Expected behavior
Files should be uploaded successfully

## Actual behavior
Getting error and identity failed .

## Screenshots
![logoissue](https://user-images.githubusercontent.com/34593983/86903789-72af4680-c12d-11ea-9d58-49cda7e3df1a.png)
![logoissueq](https://user-images.githubusercontent.com/34593983/86903794-73e07380-c12d-11ea-8e3c-494cea85b2f4.png)

## Desktop (please complete the following information):
 - OS:  Ubuntu 18
 - Gluu version 4.2

**Comment by syntrydy** [comment] 2020-07-08 12:17
@MohitMaliFtechiz can you collect log and add here? Because me i'm able to add.

**Comment by syntrydy** [comment] 2020-07-08 12:45
![image](https://user-images.githubusercontent.com/7513418/86920138-2e1dae00-c121-11ea-93f2-c8cafd8b9bf6.png)

**Comment by syntrydy** [comment] 2020-07-09 12:50
@MohitMaliFtechiz, 'i'm closing this because it is not reproducible.
Feel free to open you can replicate with the latest war.

**Closed by syntrydy** 2020-07-09 12:50 UTC
Labels: bug, exclude from release notes
