### ISSUE TITLE
'Generate' method in SAML Trust relationship throwing NPE

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#368] opened 2016-10-10 22:36 UTC
How to reproduce the issue: 
- Grab 2.4.4 SP2 ( oxAuth, oxTrust and oxIDP )
- Log into oxTrust
- SAML --> Trust Relationships
  - 'Add Relationship'
    - DisplayName: anything
    - Description: anything
    - Metadata Type: Generate
    - URL: https://sp.gluu.org
    - Hit 'Add'  
      Getting 'System Error' from oxTrust. 

'oxtrust.log' showing: 

```
2016-10-10 15:26:10,915 ERROR [org.jboss.seam.exception.Exceptions] handled and logged exception
javax.servlet.ServletException: java.lang.NullPointerException
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
        at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98)
        at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:86)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
        at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.faces.el.EvaluationException: java.lang.NullPointerException
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:101)
        at javax.faces.component.UICommand.broadcast(UICommand.java:315)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:786)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1251)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
        ... 40 more
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at org.gluu.oxtrust.ldap.service.SSLService.getPEMCertificateStatic(SSLService.java:109)
        at org.gluu.oxtrust.ldap.service.SSLService.getPEMCertificate(SSLService.java:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
        at org.gluu.oxtrust.ldap.service.SSLService_$$_javassist_seam_65.getPEMCertificate(SSLService_$$_javassist_seam_65.java)
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.getCertForGeneratedSP(UpdateTrustRelationshipAction.java:432)
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.save(UpdateTrustRelationshipAction.java:244)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.security.SecurityInterceptor.aroundInvoke(SecurityInterceptor.java:163)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction_$$_javassist_seam_57.save(UpdateTrustRelationshipAction_$$_javassist_seam_57.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:335)
        at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:348)
        at org.jboss.el.parser.AstPropertySuffix.invoke(AstPropertySuffix.java:58)
        at org.jboss.el.parser.AstValue.invoke(AstValue.java:96)
        at org.jboss.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:276)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
        ... 48 more
```
- Gluu Server version
  - oxAuth: 

```
[root@seven webapps]# cat /opt/tomcat/webapps/oxauth/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxAuth Server
Implementation-Version: 2.4.4.sp2
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: 1b3542caae0759fbc3da1270bb8c563c96c60cd0
Archiver-Version: Plexus Archiver
```
- oxTrust: 

```
[root@seven webapps]# cat /opt/tomcat/webapps/identity/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 2.4.4.sp2
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: 32e5f
Archiver-Version: Plexus Archiver
```

**Comment by shekhar16** [comment] 2016-10-29 12:15
@mzico its not a problem.this exception occurred because there is no file uploaded for 'Public certificate'.
in this case we are creating this certificate from back end,if needed we can remove this exception. please let me know.

**Comment by mzico** [comment] 2016-10-31 10:56
@shekhar16 : yes. Let's make it in this way... 
If cert is not supplied, IDP will generate a self signed cert and key for this trust relationship. This cert and key will be included in 'Shibboleth zip' file which user will use to configure his/her SP.

**Comment by mzico** [comment] 2017-03-13 13:33
@zamilskhan : Can we check if it's working in 3.0.1?

**Comment by zamilskhan** [comment] 2017-03-14 01:26
@mzico I did not see the exception NPE, but found a different error. Please see the stack trace in [this link](https://pastebin.com/2Axz5Hk3).

**Comment by mzico** [comment] 2017-03-14 05:42
@zamilskhan : Thanks. To me, it's not complete in 3.0.1. 
May be it will be completed properly in 3.1.0. @shekhar16 : thoughts?

**Comment by nynymike** [comment] 2017-04-08 02:49
This needs to work in both 2.4.x and 3.0.x. Can you confirm if the current shipping versions still have this error. If so, we need to assign.

**Comment by willow9886** [comment] 2017-04-10 16:57
This **has to work in 3.x**

**Comment by willow9886** [comment] 2017-04-10 19:21
Comment from @mzico :

> This work individually... 
> But.. I think it's breaking general SP operation. 

> Alex/Sahil/Zamil, can you please confirm it's working properly. 

> Here is how we can check: 

> - Add a SP ( testShib we can try, remember to remove SingleLogout URI.. otherwise testShib won't recognize our metadata ). 
> - See if this metadata location is populated properly in metadata-provider.xml 
> - Try to add another SP ( this time... you can just use any native Shibboleth SP )
> - See Shibboleth SP's metadata is appended in metadata-provider.xml or not. 
> - Check SSO for Shibboleth SP and TestShib. 
> - If both SSO works, try to use Generate.

**Comment by shekhar16** [comment] 2017-05-03 18:54
@aliaksander-samuseu @mzico @sahiliamsso please confirm the issue.if fixed please close it.

**Comment by shekhar16** [comment] 2017-05-08 15:18
[8:44:15 PM | Edited 8:44:21 PM] Shekhar L: Hi Dmitry
[8:44:45 PM] Dmitry Ogn: Hi Shekhar
[8:45:28 PM] Shekhar L: Can u please help me on issue for which Yuriy M created the conversation
[8:45:47 PM] Dmitry Ogn: Yeah
[8:45:55 PM] Shekhar L: I m facing CAS issue on SAml validation
[8:46:17 PM] Shekhar L: and I think both are independent
[8:46:49 PM] Dmitry Ogn: I'll fix it.
[8:47:05 PM] Shekhar L: ok

**Comment by shekhar16** [comment] 2017-08-05 07:52
I tested it in 3.1.0 latest code its working.
![image](https://user-images.githubusercontent.com/15937500/28993985-bd8003a8-79e0-11e7-836e-2787e6ed8063.png)

**Comment by shekhar16** [comment] 2017-08-20 15:36
@mzico @aliaksander-samuseu  Please let me know the issue is it working for you?

**Comment by mzico** [comment] 2017-08-20 19:09
@shekhar16 : Unfortunately not in my case. 
See... when I select 'Generate'; no 'URi' input box is coming. 

This is the version of oxTrust: 

```
GLUU.root@localhost:/install/community-edition-setup# cat /opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-5447289375881717487.dir/webapp/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.1.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 38a8a18a64efe935cd5d00d5011989adc0d7971c
Implementation-Vendor-Id: org.xdi
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_121

```

![screenshot_12](https://user-images.githubusercontent.com/7156097/29497634-2da48cd6-85b1-11e7-854c-8dbb6df8760d.png)

**Comment by shekhar16** [comment] 2017-08-21 18:39
I m closing this issue.Please reopened it if found any related isssue.

**Closed by shekhar16** 2017-08-21 18:39 UTC
Labels: bug, High Priority, QA
