### ISSUE TITLE
'Import people' feature not working

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#102] opened 2015-08-24 11:46 UTC
Gluu Server version: 2.3.3 

Situation: Tried to import a xls file ( Users --> Import people --> Upload xls file ). But oxTrust is failing to accept the xls file with error `Import failed, there are similar UID(s) in input file`. The 'Username' of xls sheet has different Usernames for every users. 

[Sample xls file](http://ox.gluu.org/lib/exe/fetch.php?media=new_users.xls)

![import_people](https://cloud.githubusercontent.com/assets/7156097/9439322/854c32e0-4a2b-11e5-9481-c54acfd0eff0.png)

No indication of error in logs. Stack trace: 

    INFO   | jvm 1    | 2015/08/24 11:35:27 | 2015-08-24 11:35:27,572 INFO  [org.gluu.oxtrust.action.PersonImportAction] Found 4 persons in input Excel file                                                                                                                                                  
    INFO   | jvm 1    | 2015/08/24 11:35:27 | 2015-08-24 11:35:27,932 DEBUG [org.gluu.oxtrust.servlet.FaviconImageServlet] Starting organization favicon  upload

**Comment by rahatjaan** [comment] 2015-08-27 09:47
can you attach sample xl file which can be used to reproduce the issue

**Comment by mzico** [comment] 2015-08-27 10:13
@rahatjaan : It's not possible to attach files here in github, I guess. I'll send you over email.

**Comment by rahatjaan** [comment] 2015-08-27 13:03
there are two issues I found..

1) The input file zico shared with me is invalid... it has almost 60 empty rows and the columns are required so it will be failed to import
2) We must have importPerson.properties in tomcat/conf directory , otherwise import feature will not work

**Comment by rahatjaan** [comment] 2015-08-27 15:23
https://github.com/GluuFederation/community-edition-setup/commit/0201078716ff3c4493274e7bf91af83d89d35754

**Comment by rahatjaan** [comment] 2015-08-27 15:24
I have added gluupersonimport.properties file to community-setup

**Comment by yurem** [comment] 2015-08-27 16:04
Updated setup to copy it to conf during install https://github.com/GluuFederation/community-edition-setup/commit/f4ef3dd2f4850e3aa112a961ef921974e813f6cd

**Comment by rahatjaan** [comment] 2015-09-10 09:29
can we close this ticket now???

**Comment by yurem** [comment] 2015-09-10 16:12
I think so

**Comment by chudsonsolomon** [comment] 2015-09-29 14:10
I am using 2.3.4-2 version. Import users option doesn't work.
This same problem i faced in previous versions. The logs doesn't related to this error..

**Comment by yurem** [comment] 2015-10-16 14:00
@zico, can you retest it and attach xml file if this not work fine

**Comment by willow9886** [comment] 2016-01-29 21:47
Looks like Yura added a fix for this issue. Closing.

**Comment by willow9886** [comment] 2016-01-29 22:22
@yurem can you double check this fix? @aliaksander-samuseu is reporting that it is not fixed, and is blocking progress on #161

**Comment by shekhar16** [comment] 2016-01-31 04:45
@willow9886 this issue is fixed and i checkin the code in repository.Please check it .

**Closed by shekhar16** 2016-01-31 04:45 UTC
Labels: bug, High Priority
