### ISSUE TITLE
Reset password page error handling / Strong password policy

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#2307] opened 2023-02-15 10:13 UTC
Currently if we implement strong password policy ( https://github.com/GluuFederation/support-docs/blob/master/howto/PasswordReset/strongPasswordReset.md)  in Gluu's oxTrust password, password reset page throwing just "Oops" page upon entering simple password.  It would be great to show a banner like below. It will be easier for user to understand why his/her password not invited by Gluu Server. 

![Screenshot from 2023-02-15 16-12-26](https://user-images.githubusercontent.com/7156097/218998756-2b270ca0-4f8b-4ccc-8b8b-ace01edbea43.png)

**Comment by shekhar16** [comment] 2023-05-01 22:00
The issue is fixed raised above PR..
here is the screenshot.
![image](https://user-images.githubusercontent.com/15937500/235539124-c39f439a-7f0a-41f6-8313-1a61e8547fc6.png)

**Comment by shekhar16** [comment] 2023-05-05 10:26
@mzico  verified it. 
Closing this ticket.
Thanks :)

**Closed by shekhar16** 2023-05-05 10:26 UTC
