### ISSUE TITLE
UI throw exception

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#712] opened 2017-09-05 01:24 UTC
Getting below error even when session was not idle for 5mins. 

![image](https://user-images.githubusercontent.com/21104811/30041275-5acf1e4a-9206-11e7-8d66-478a3d9b28e4.png)

In some cases (behavior is not fixed), still getting this error. 

![image](https://user-images.githubusercontent.com/21104811/30041331-e73902ec-9206-11e7-977b-60c2dae5053b.png)

oxtrust logs
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
2017-09-05 01:23:20,418 ERROR [qtp985655350-19] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:54) - null
java.lang.NullPointerException: null
        at org.richfaces.component.util.SelectUtils$GenericObjectSelectItem.updateItem(SelectUtils.java:78) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.util.SelectUtils$GenericObjectSelectItem.access$100(SelectUtils.java:49) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.util.SelectUtils$GenericItemsIterator.computeNext(SelectUtils.java:136) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.util.SelectUtils$GenericItemsIterator.computeNext(SelectUtils.java:115) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:?]
        at org.richfaces.component.util.SelectUtils$SelectItemsIterator.computeNext(SelectUtils.java:158) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.util.SelectUtils$SelectItemsIterator.computeNext(SelectUtils.java:146) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:?]
        at org.richfaces.renderkit.SelectManyHelper.getClientSelectItems(SelectManyHelper.java:252) ~[richfaces-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.renderkit.SelectManyRendererBase.getClientSelectItems(SelectManyRendererBase.java:64) ~[richfaces-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.renderkit.html.PickListRenderer.doEncodeEnd(PickListRenderer.java:214) ~[richfaces-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.renderkit.RendererBase.encodeEnd(RendererBase.java:180) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:312) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]

**Comment by yurem** [comment] 2017-09-07 07:44
It's no session/conversation issue according to logs. It's sometging wrong with selection UI elements. Can you give full stack trace and what you did to get it?

**Comment by shekhar16** [comment] 2017-09-10 14:03
@sahiliamsso  please add more description and scenario to reproduce the issue.

**Comment by shekhar16** [comment] 2017-09-13 17:10
@sahiliamsso  Can i close this issue ?

**Comment by sahiliamsso** [comment] 2017-09-26 01:32
When we leave session idle for more than 15mins , then we get this error.

**Comment by shekhar16** [comment] 2017-09-29 04:20
Sorry @sahiliamsso  it is not reproduced yet.Please mention the scenario.

**Comment by yurem** [comment] 2017-10-01 20:56
I closed it because according to stack trace in description it's application error. App can't convert one selectable item. We need to know exact place where it happens to fix it. You added only one part of this stack trace which not shows root case.

**Closed by yurem** 2017-10-01 20:56 UTC
