### ISSUE TITLE
StatusCheckerTimer check_ssl retuned an unexpected value

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#238] opened 2016-04-22 15:03 UTC
An exception from 2.4.3 1_3 (final) Tomcat log (clear gluu CE, after installation):
INFO   | jvm 1    | 2016/04/22 14:54:17 | 2016-04-22 14:54:17,661 ERROR [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] There was an error executing command check_ssl
INFO   | jvm 1    | 2016/04/22 14:54:17 | 2016-04-22 14:54:17,661 ERROR [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] check_ssl retuned an unexpected value
INFO   | jvm 1    | 2016/04/22 14:55:16 | org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.xdi.util.process.ProcessHelper.executeProgram(ProcessHelper.java:150)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.xdi.util.process.ProcessHelper.executeProgram(ProcessHelper.java:65)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.xdi.util.process.ProcessHelper.executeProgram(ProcessHelper.java:45)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.xdi.util.process.ProcessHelper.executeProgram(ProcessHelper.java:39)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.runCheck(StatusCheckerTimer.java:196)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.setCertificateExpiryAttributes(StatusCheckerTimer.java:170)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.process(StatusCheckerTimer.java:130)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.scheduleStatusChecking(StatusCheckerTimer.java:93)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.async.AsynchronousInterceptor.aroundInvoke(AsynchronousInterceptor.java:52)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.gluu.oxtrust.ldap.service.StatusCheckerTimer_$$_javassist_seam_7.scheduleStatusChecking(StatusCheckerTimer_$$_javassist_seam_7.java)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.async.AsynchronousInvocation$1.process(AsynchronousInvocation.java:62)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.async.Asynchronous$ContextualAsynchronousRequest.run(Asynchronous.java:80)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.async.AsynchronousInvocation.execute(AsynchronousInvocation.java:44)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at org.jboss.seam.async.ThreadPoolDispatcher$RunnableAsynchronous.run(ThreadPoolDispatcher.java:142)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/04/22 14:55:16 |       at java.lang.Thread.run(Thread.java:745)

**Comment by dmogn** [comment] 2016-04-22 16:02
Ubuntu 14.04

**Comment by dmogn** [comment] 2016-04-22 16:21
check_ssl
unable to load certificate
140205151905440:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: TRUSTED CERTIFICATE
Traceback (most recent call last):
  File "/usr/local/bin/check_ssl.py", line 13, in <module>
    time_tup = time.strptime(t, '%b %d %H:%M:%S %Y %Z')
  File "/usr/lib/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%b %d %H:%M:%S %Y %Z'

**Comment by aliaksander-samuseu** [comment] 2016-04-23 01:34
Hi, @dmogn . When exactly this happen? Does it interrupt any vital functionality? Can it be perceived as critical issue?

**Comment by dmogn** [comment] 2016-04-25 00:51
Hi, @aliaksander-samuseu!
It happen directly after installation (setup.py). No errors in setup.log. 

oxTrust calls check_ssl in cycle (~5 sec), but check_ssl does not work.

**Comment by yurem** [comment] 2016-04-25 06:25
I can't reproduce it. But I probably know why this happens only in your VM.

O suspect you uses not en_US locale.

Here is source code of this python program:
https://github.com/GluuFederation/gluu-util/blob/master/check_ssl/check_ssl.py
It's very simple but run OS command and parse output.

Can you run (please replace % with hostname):
'echo | openssl s_client -connect %s:443 2>/dev/null | openssl x509 -noout -dates|grep -i notafter'

If my idea is right we need to add:
LC_ALL=en_US to the start of this command to set locale explicitly.

**Comment by aliaksander-samuseu** [comment] 2016-04-27 21:19
@dmogn , we have a user [reporting problems with accessing service right after installing it](https://support.gluu.org/installation/ubuntu-web-interface-does-not-load-2673#at10058) on Linode's vm. We couldn't find what is wrong with his configuration, but the wrapper.log of the service starting that he provided [here](http://pastebin.com/zUS36cy6) also contains the error about check_ssl failing. Could you check this ticket and give a judgement whether or not it's the same issue you are reporting here?

**Comment by yurem** [comment] 2016-04-28 08:49
@vishwa724 Can you check this issue?

**Comment by dmogn** [comment] 2016-04-29 17:38
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=es_UY.UTF-8
LC_TIME=es_UY.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=es_UY.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=es_UY.UTF-8
LC_NAME=es_UY.UTF-8
LC_ADDRESS=es_UY.UTF-8
LC_TELEPHONE=es_UY.UTF-8
LC_MEASUREMENT=es_UY.UTF-8
LC_IDENTIFICATION=es_UY.UTF-8
LC_ALL=

**Comment by dmogn** [comment] 2016-04-29 17:48
@yurem: I cannot change to en_US inside gluu-server
locale -a    
C
C.UTF-8
POSIX

**Comment by dmogn** [comment] 2016-04-29 18:11
Fixed.
The command chain inside gluu-server login:
# locale-gen en_US.utf8
# locale -a
C
C.UTF-8
POSIX
en_US.utf8
#export LC_ALL=en_US
-su: warning: setlocale: LC_ALL: cannot change locale (en_US): No such file or directory
locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LANGUAGE=
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=en_US
# check_ssl
357

- there are warnings of locale, but check_ssl now works.

**Comment by dmogn** [comment] 2016-04-29 18:16
Hm... now check_ssl works after relogin too, with POSIX locale....

**Comment by uboznikov** [comment] 2016-07-18 10:06
I'm getting this issue in v2.4.4 RC1 in CentOS 6.8. Initially after installation this did not occur, and now Apache is not starting anymore.

I tried below commands to no avail:

`localedef -c -f UTF-8 -i en_US en_US.UTF-8`
`export LC_ALL=en_US.UTF-8`
`export LANG=en_US.UTF-8`

Test follows:

```
GLUU.[root@v244 logs]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

```
GLUU.[root@v244 logs]# check_ssl
unable to load certificate
139828030945096:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: TRUSTED CERTIFICATE
Traceback (most recent call last):
  File "/usr/local/bin/check_ssl.py", line 13, in <module>
    time_tup = time.strptime(t, '%b %d %H:%M:%S %Y %Z')
  File "/usr/lib64/python2.6/_strptime.py", line 454, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.6/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%b %d %H:%M:%S %Y %Z'

```

**Comment by uboznikov** [comment] 2016-07-18 10:13
In Ubuntu 14.04 this is ok:

```
GLUU.root@v244:~# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

```
GLUU.root@v244:~# check_ssl
364
```

**Comment by ganesh-at-wiw** [comment] 2016-08-08 19:28
Anything required in this issue on my part?

**Comment by yurem** [comment] 2016-08-08 20:24
I offer to close this issue.
We need to replace this command with java code: https://github.com/GluuFederation/oxTrust/issues/308

**Closed by yurem** 2016-08-08 20:24 UTC
Labels: bug
