### ISSUE TITLE
Remove Attribute not working

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#309] opened 2016-07-25 20:00 UTC
[According to this issue](https://support.gluu.org/maintenance/cant-delete-custom-attribute-from-oxtrust-gui-3020), remove attribute wasn't working.  Note: you need to you `dsconfig` cli tool to update schema in a live ldap server.

**Comment by aliaksander-samuseu** [comment] 2016-07-28 01:23
Confirmed.

Here are steps I used:

1. Create 2 custom attributes
2. Assign some values to them. I used CR to populate them, but it's quite possible you don't need this, just make sure you'll create 2-5 user entries and assign some value for both these custom attributes for all users. But I have suspicion that race condition situation may take place, so it's better to use a larger userbase (I used ~5k user entries) if you won't be able to reproduce it for 2-5 users
3. Create 2 SAML TRs with any metadata you like. Assign one attribute to 1st TR, and both attributes to 2nd (I don't actually think this step is needed, just mentioning what I did during reproduction)
4. Now delete 1st attribute, then try to delete 2nd one **right away**

Result:
1st attribute is successfully deleted (its definition is also being removed from schema and from `ox-*` custom objectclass), but upon attempt to delete the 2nd one "system error" message appears in web UI, and java exception is registered in the `wrapper.log` (please see it in the attachment).

My guess about what is happening:
As you can see from log, it complains about inability to change/persist some user entry under "ou=people".  I checked this entry, there is nothing special about it, aside from the fact that it still has values assigned to both attributes (including one that I deleted and that was removed from schema). So it seems that upon deletion of the 2nd custom attribute Gluu attempts to update user entries with goal in mind unknown to me, but can't as these entries contain now non-existing attribute - the one you removed first.

If after this issue is already encountered you'll try to create another attribute, then immediately remove it, it succeeds. So it seems to affect only cases when some user entries have some values assigned to these attributes only.

**Comment by shekhar16** [comment] 2016-07-28 17:50
@yurem I analyzed the issue and as per my findng there is an exception thrown to modify the person record.The exception is 
LDAPException(resultCode=65 (object class violation), errorMessage='Entry inum=@!8214.2DD7.3392.F903!0001!AE01.CC82!0000!E6BC.BA68,ou=people,o=@!8214.2DD7.3392.F903!0001!AE01.CC82,o=gluu cannot be modified because the resulting entry would have violated the

**Comment by aliaksander-samuseu** [comment] 2016-07-28 18:13
@shekhar16 @yurem 

The question probably is how oxTrust should behave when somebody tries to remove attribute from the scheme when for some user entries it has already been assigned some values? Should it reject attribute deletion request? Should it warn user that he must first clear this attribute of values for all user entries? Should it do this cleaning automatically (and what performance it will show in case of tens or hunderds thousands user entries)?

**Comment by shekhar16** [comment] 2016-07-28 18:55
Attribute are automatically get clean from all user entries.All user Entries get update by removing this attribute from there record.

**Comment by nynymike** [comment] 2016-11-29 04:14
@shekhar16 Please confirm that this works with new attribute registration workflow.

**Comment by shekhar16** [comment] 2016-12-18 07:35
Yes I done the new attribute registration flow.And now it s under on Yuriy's plate to verify and approval.

**Comment by yurem** [comment] 2017-01-04 17:12
@nynymike in old implementation before remove attribute from schema we call [method ](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ldap/service/AttributeService.java#L381) to remove it from all user/TR entries.

Should we clean all user/TR entries now before unregistered attribute.

**Comment by yurem** [comment] 2017-01-12 21:00
Fixed, now it's possible to remove custom attributes

**Closed by yurem** 2017-01-12 21:00 UTC
Labels: bug
