### ISSUE TITLE
Failed to update entry error in new installation

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#443] opened 2017-01-14 20:07 UTC
OS: CentOS 6.6 (Final)
Package: gluu-server-3.0.0.x86_64                                                  9-BETA2.centos6
The `oxtrust.log` file shows the following error in a fresh new untouched installation.
```
2017-01-14 20:06:01,751 ERROR [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:171) - Failed to update current appliance
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to update entry: inum=@!8B81.B40A.F123.6C32!0002!1CFA.4488,ou=appliances,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:182) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:268) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:283) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.ldap.service.ApplianceService.updateAppliance(ApplianceService.java:70) ~[classes/:?]
        at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source) ~[?:?]
at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to update entry: inum=@!8B81.B40A.F123.6C32!0002!1CFA.4488,ou=appliances,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:176) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        ... 58 more
```

**Comment by yurem** [comment] 2017-01-15 16:44
Can you add rest of the stack trace to understand which LDAP error led to this issue.

**Comment by dmogn** [comment] 2017-01-16 02:38
I got same error on gluu-server-3.0.0_9-BETA2~trusty+Ub14.04_amd64.deb:

2017-01-16 02:31:20,617 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:382) - Setting facter attributes
2017-01-16 02:31:20,744 ERROR [pool-2-thread-10] [org.gluu.oxtrust.ldap.service.StatusCheckerDaily] (StatusCheckerDaily.java:123) - Failed to update current appliance
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to update entry: inum=@!6829.A7C8.4D64.6ABE!0002!B928.C5CD,ou=appliances,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:182) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:268) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:283) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.ldap.service.ApplianceService.updateAppliance(ApplianceService.java:70) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.gluu.oxtrust.ldap.service.ApplianceService_$$_javassist_seam_16.updateAppliance(ApplianceService_$$_javassist_seam_16.java) ~[classes/:?]
        at org.gluu.oxtrust.ldap.service.StatusCheckerDaily.processInt(StatusCheckerDaily.java:121) [classes/:?]
        at org.gluu.oxtrust.ldap.service.StatusCheckerDaily.process(StatusCheckerDaily.java:86) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.async.AsynchronousInterceptor.aroundInvoke(AsynchronousInterceptor.java:52) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.gluu.oxtrust.ldap.service.StatusCheckerDaily_$$_javassist_seam_41.process(StatusCheckerDaily_$$_javassist_seam_41.java) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.Component.callComponentMethod(Component.java:2313) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.Events.raiseEvent(Events.java:85) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.async.AsynchronousEvent$1.process(AsynchronousEvent.java:33) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.async.Asynchronous$ContextualAsynchronousRequest.run(Asynchronous.java:80) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.async.AsynchronousEvent.execute(AsynchronousEvent.java:27) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.async.ThreadPoolDispatcher$RunnableAsynchronous.run(ThreadPoolDispatcher.java:142) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_112]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_112]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to update entry: inum=@!6829.A7C8.4D64.6ABE!0002!B928.C5CD,ou=appliances,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:176) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        ... 60 more
2017-01-16 02:31:22,022 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:505) - Setting facter param: memoryfree
2017-01-16 02:31:22,023 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:525) - memoryfree => 4.60 GB

**Comment by yurem** [comment] 2017-01-16 10:11
Fixed in: http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.0-SNAPSHOT/oxtrust-server-3.0.0-SNAPSHOT.war

**Closed by yurem** 2017-01-16 10:11 UTC

**Comment by zamilskhan** [comment] 2017-01-16 18:16
Thanks @yurem
