### ISSUE TITLE
Improve the "Relying party configuration" pop up 

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#825] opened 2018-01-31 13:51 UTC
Environment:
CentOS release 6.9 (Final), gluu-server-3.1.2-1-7.centos6

Steps to reproduce:
1. Log in to web UI as admin
2. Proceed to "SAML -> Add trust relationship"
3. Set "Entity Type" to "Single SP"
4. Set "Configure Relying Party" checkbox and in pop-up window that will appear add "SAML2SSO" and "Artifact resolution" profiles to the list

Result:
The pop-up is not in good shape. It looks ok when just one profile is selected, but after another one is added, it becomes twisted (please see the picture below):
![relparty_popup_issues](https://user-images.githubusercontent.com/11802046/35626521-04607098-06a7-11e8-90e6-fe08150e522d.png)
1. This strange indent marked with arrow, looks very clumsy
2. There is no vertical scrolling bar for the whole window, only ones for the specific profile items. So the only way to scroll to the next profile item in the list is to use mouse wheel, what is not good

**Comment by shekhar16** [comment] 2018-02-06 18:46
![image](https://user-images.githubusercontent.com/15937500/35877668-ff620e40-0b9b-11e8-9188-519567b3642f.png)

**Comment by shekhar16** [comment] 2018-02-07 15:11
@aliaksander-samuseu  I fixed it and above i had pasted snapshot.I m closing this issue if u found anything in that please reopen it and let me know.

**Comment by yurem** [comment] 2018-02-08 06:22
Can you add link to commit? We need to make sure that we put fix into 3.1.3 too

**Comment by shekhar16** [comment] 2018-02-08 17:47
Cherry pic is done for 3.1.3 version

**Comment by shekhar16** [comment] 2018-04-14 10:41
the issue is reopened for chrome.
Fixed.
![image](https://user-images.githubusercontent.com/15937500/38767425-6db854e4-3ffe-11e8-956d-6eed68c81e95.png)

**Closed** 2018-04-14 10:45 UTC
Labels: bug
