### ISSUE TITLE
Custom Scripts fail to update

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#637] opened 2017-08-02 08:13 UTC
Package: gluu-server-3.1.0.x86_64 1-1.BETA4.centos6
Steps to reproduce:

1. Navigate to `Manage Custom Scritps` and try to enable any custom script to see the following
![user-registration-update-error](https://user-images.githubusercontent.com/7703245/28863810-2f6b844e-778c-11e7-89fe-afe0448675f2.png)

2. The error produces the following stack trace in `oxtrust.log` available @ https://pastebin.com/JZuCQJvS

3. Stack trace produced with `Regsiter` page which shows the oxTrust login page.

**Comment by shekhar16** [comment] 2017-08-06 14:55
I think the issues with existing record in ldap for inum : @!26AF.7366.6400.ACC1!0001!10A0.3CF7!0011!2DAF.F996
Can u please share the record : inum=@!26AF.7366.6400.ACC1!0001!10A0.3CF7!0011!2DAF.F996,o
u=scripts,o=@!26AF.7366.6400.ACC1!0001!10A0.3CF7,o=gluu

**Comment by shekhar16** [comment] 2017-08-10 18:32
Please share the record so that we can resolve the issue and close it.

**Comment by rajnikantsh** [comment] 2017-08-11 09:12
Not able to reproduce this as i updated custom script by checking enable checkbox. Was able to successfully update custom script list. 
I got error while updating custom script few weeks back at that my code and data in ldap server were up to date. As i updated my data and code everything started to working fine.

**Comment by ldeveloperl1985** [comment] 2017-08-11 13:29
I am trying to update custom script using oxtrust. It updated the configuration but shows the same message as above `failed to update custom script configuration`.
oxtrust log: https://pastebin.com/YmdwJQru

Package: gluu-server-3.1.0_1-1.RC1-trusty+Ub14.04_amd64
Ubuntu 14.04

**Comment by nynymike** [comment] 2017-08-11 13:38
I wonder if it's a schema error:

```
Caused by: com.unboundid.ldap.sdk.LDAPException: modify/add operation requires values
```
Perhaps if we could print the entry to the debug log and see what value is missing.

**Comment by yurem** [comment] 2017-08-15 11:35
Can you retest in RC3? I can't reproduce it

**Closed by yurem** 2017-08-15 11:35 UTC
Labels: bug
