### ISSUE TITLE
Consent page not appearing for 'Persistent Client Authorizations' ( version: 2.4.x ) 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#206] opened 2016-02-29 22:29 UTC
How to reproduce: 

* Log into oxTrust
* OpenID Connect --> Clients
* Select 'oxTrust Admin GUI'
   - 'Persistent Client Authorizations' : False
* Save client. 
* Try to login. 

We should get a message like below image: 

![consent_message](https://cloud.githubusercontent.com/assets/7156097/13411208/90373b94-df01-11e5-8cd8-cffe7a631eec.png)

**Comment by nynymike** [comment] 2016-02-29 22:42
There are two controls that control whether the scope approval is required : pre-authorization (which totally supresses) and persist authorization, which should just require approval the first time.

**Comment by shekhar16** [comment] 2016-03-17 08:36
Fixed.Please test it
Is it behaving as expected or not?

**Comment by shekhar16** [comment] 2016-03-17 12:11
Changes reviewed by Yuriy M, and he is fine with the changes..

**Comment by mzico** [comment] 2016-03-17 12:14
@shekhar16 : which version should we check?

**Comment by yurem** [comment] 2016-03-26 14:34
It should be in 2.4.3. We deployed this update to ce-dev

**Comment by aliaksander-samuseu** [comment] 2016-04-11 19:50
Just have tried it in gluu-server-2.4.3 2-beta2 deb package. Though consent window appears, despite 
"Persist Client Authorizations* and "Pre-Authorization" both set to "True" for "oxTrust Admin GUI" client, it doesn't remember my choice and I'm being asked for consent each time I log in to oxTrust anyway.

**Comment by aliaksander-samuseu** [comment] 2016-04-12 22:44
@shekhar16 , @willow9886 I've tested it more thoroughly (the same package).

More about issue reported before. It seems it works like that when no value is assigned to the `oxPersistClientAuthorizations` LDAP attribute of the  "oxTrust Admin GUI" client (which represents "Persist Client Authorizations" setting of web UI), even despite the fact that `oxAuthTrustedClient` attribute (which represents "Pre-Authorization" setting) is set to true (and thus shouldn't be affected by the former one, as far as my understanding goes). This is how it was from the moment I installed the instance, i.e. in web UI it was showing me that "Persist Client Authorizations" setting is set to "true", but in LDAP the attribute was empty (see picture below):

![persist_clnt_authz](https://cloud.githubusercontent.com/assets/11802046/14475486/d95a12da-010a-11e6-9fbc-b2dc68bfd0cb.jpg)
That doesn't seem right on itself, this value should have some explicit value initially, I believe.

If you update the client config in web UI or directly assign "true" to this attribute in LDAP, it stops ask consent each time you login to oxTrust as admin, at least. Though there are other issues with this feature, please see chart below:

![authz-controls](https://cloud.githubusercontent.com/assets/11802046/14477829/37aa3ef6-0119-11e6-98c7-e7a71117e5e5.jpg)

**Comment by yurem** [comment] 2016-04-22 06:42
Here is my point of view on this issue:

  if (Pre-Authiorization exists and set to True):
    // Allows to log in without asking for consent
  else:
    if (Persist_Client_Authorizations exists and set to True)
      // Allows to log in without asking for consent
    else:
      // Asks for consent

@mike, please review it

**Comment by yurem** [comment] 2016-04-22 06:45
This workflow also covers case when there are no these attributes in client entry. We can't expect the client entry will contains them by default.
@shekhar16 Once you will did that you should check 3x3 = 9 combinations of these 2 attributes to make sure that it works as expected

**Comment by mzico** [comment] 2016-04-22 11:11
Hey Guys! 

@yurem @shekhar16 : I think it's working now in 2.4.3.

**Comment by aliaksander-samuseu** [comment] 2016-04-23 02:35
@mzico , In my 2.4.3-1-3 it doesn't seem to be different from what I described in that table in my previous post. I.e. it still doesn't remember user choice, and "oxAuthTrustedClient" does not override the other setting.

@yurem , shouldn't it be more like that?

    if (Pre-Authiorization exists and set to True):
      // Allows to log in without asking for consent
    else:
      if (Persist_Client_Authorizations exists and set to True)
       if (Authorization_decision is already persisted for this user)
          // Allows to log in without asking for consent
       else:
        // Asks for consent, allows to login if "Yes", persists user's Authorization_decision
      else:
        // Asks for consent

**Comment by aliaksander-samuseu** [comment] 2016-04-23 02:41
Btw, what if "Persist_Client_Authorizations" is set to "true" and user will decide to not allow it this time? Should it persist his decision in that case, thus effectively blocking his from any subsequent attempts to use the service? Or is there some king of timeout/cooldown period for the persisted decisions?

**Comment by nynymike** [comment] 2016-04-23 21:50
We don't have any interface for the user to review or revoke authorizations.

**Comment by yurem** [comment] 2016-04-25 07:01
@aliaksander-samuseu 
yes, I omitted this part because it's subject of this issue:

        // Allows to log in without asking for consent
     else:
      // Asks for consent, allows to login if "Yes", persists user's Authorization_decision

**Comment by shekhar16** [comment] 2016-05-03 18:15
Fixed.
@aliaksander-samuseu please verify it.

**Comment by yurem** [comment] 2016-05-03 19:12
We need to check it on [this](http://ox.gluu.org/maven/org/xdi/oxauth-server/2.4.3-SNAPSHOT/oxauth-server-2.4.3-SNAPSHOT.war) build.

**Comment by yurem** [comment] 2016-05-04 10:39
It looks like it works. But we can get same issue back again after some changes in the future. We need to cover it by tests to save this effort :)

Pre-Authorization is covered by test already: AuthorizeRestWebServiceHttpTest.requestAuthorizationPromptConsentTrustedClient

We need to copy this test into new test to cover Persist_Client_Authorizations. In this test we need to request authorization 2 times:
1) authenticateResourceOwnerAndGrantAccess
2) authenticatePreAuthorizedResourceOwnerAndGrantAccess

And change
        registerRequest.addCustomAttribute("oxAuthTrustedClient", "true");
with
        registerRequest.addCustomAttribute("oxAuthTrustedClient", "false");

@shekhar16 can you do this?

**Comment by yurem** [comment] 2016-05-04 12:39
There is new bug in latest code: https://github.com/GluuFederation/oxTrust/issues/243

It appears only when I try to log in using client with Pre-Authorization=True
The application not redirect user to proper page

**Comment by aliaksander-samuseu** [comment] 2016-05-04 17:08
@yurem , then I suppose it's better to wait before that new issue is also fixed, and test both fixes after that.

**Comment by aliaksander-samuseu** [comment] 2016-05-07 20:09
@yurem I've given a try to build you provided above where consent dialog should be fixed. It indeed now doesn't show dialog for trusted clients, and it's able to memorize the user choice for non-trusted clients with Persist Authz flag set to true. But for clients for each both flags are false it behaves as in previous case (asks ones, remember choice), while it must just ask every time.

I also wasn't able to reproduce issue you mentioned.

**Comment by yurem** [comment] 2016-06-15 18:19
I think it's fixed 2.4.4 and in 2.4.3 after rebuild

**Closed by yurem** 2016-06-15 18:19 UTC
Labels: bug, High Priority
