### ISSUE TITLE
"Search" should return results (except for Person search)

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#354] opened 2016-09-20 17:44 UTC
For all search boxes in oxTrust, hitting the "Search" button should return results--except when searching for people (where two characters should be required).  If possible, specify maximum results at 25 entries or paginate.

**Comment by aliaksander-samuseu** [comment] 2016-09-20 17:47
I guess the same question could be asked about OIDC's "Client", "Scopes" etc pages too, which don't list all clients/scopes right away too.

**Comment by nynymike** [comment] 2016-09-20 17:49
If the results are paged, we maybe should just automatically display results.

**Comment by shekhar16** [comment] 2016-09-25 16:40
Fixed :).

**Comment by aliaksander-samuseu** [comment] 2016-11-05 21:29
@shekhar16 

Reopening this one, as this affects functionality and it may be reasonable to push it in SP2 for 2.4.4 packages too, if possible.

**Comment by shekhar16** [comment] 2016-11-06 18:16
@aliaksander-samuseu  the code is committed ,
But I think in SP2 updater , these code changes are not included.

**Comment by aliaksander-samuseu** [comment] 2016-11-06 18:34
@shekhar16 @willow9886 

The point is that is should be included in SP2. Who is responsible for that part? We may need to discuss this. This (and several other) fix(es) are not that complex (by look of it), but at the same time they impair web UI's functionality. As many users (including customer) will probably stay with 2.4.x instances for some time, and because of there will be significant differences in architecture between 2.4.x and 3.x (so if upgrade from 2.4.4 to 2.4.4SP2 is a piece of a cake, then upgrade from 2.4.4 to 3.0 is a BIG issue; too big if all that is needed is to fix some web UI bugs) I still think we should include in SP2 all fixes that a) are not that complex to implement b) affect functionality

**Comment by nynymike** [comment] 2016-11-29 03:40
@aliaksander-samuseu Please re-test.

**Comment by yurem** [comment] 2016-12-28 11:40
@aliaksander-samuseu can you explain what you mean "Reopening this one, as this affects functionality..."
Can you test it?

**Comment by aliaksander-samuseu** [comment] 2017-01-12 00:04
I've just checked it for [this](https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-server-3.0.0_6-BETA2~trusty+Ub14.04_amd64.deb
) package, and it doesn't show the full list of existing SAML TRs when page is opened. It's even worse now, as even clicking the "Search" button with empty search input field is not enough, it doesn't display anything this way. You need actually to provide a valid search term to display something.

@yurem, back then when words you quoted were written, that fix wasn't yet added to SP2 for 2.4.4 (which was about to be released) and as Michael said we'll be supporting 2.4.4 for at least a year after 3.0 will be released, I thought we need to pack all latest fixes in there too, as some of them usually were marked like "fixed for 3.0" only. And this issue somewhat affects usability of web UI (a paying customer complained about that once), so I thought it's a good candidate to be added to SP2.

**Comment by aliaksander-samuseu** [comment] 2017-01-12 00:07
It seems the same issue affects all other pages with search feature on them, like OIDC clients/scopes page, UMA pages. It's mostly unusable atm.

**Comment by nynymike** [comment] 2017-01-12 02:48
Yes, previously we could hit search for everything except users, and it would return results. I think this was preferable. As a workaround, you can search for @--if the search is looking at the inum, that will return everything.

**Comment by shekhar16** [comment] 2017-01-12 15:03
It is working fine with latest code.on all three pages i.e TR ,scope, client.
Can u please retest it ?

**Comment by aliaksander-samuseu** [comment] 2017-01-12 15:38
@shekhar16 , what latest code? I checked it for this build of 3.0: [link](https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-server-3.0.0_6-BETA2~trusty+Ub14.04_amd64.deb), seems to be the latest available deb package in devel repo.

@nynymike 
>As a workaround, you can search for @--if the search is looking at the inum, that will return everything.

Works only for SAML TRs and OIDC clients for me, but not for OIDC scopes, or UMA items, probably some other universal search key is needed there.
But what is the intended behaviour? Should it be left like this?

**Comment by nynymike** [comment] 2017-01-12 17:30
IMHO, no... I think hitting the search button should return results.

**Comment by shekhar16** [comment] 2017-01-13 04:07
@nynymike Sorry i couldn't able to reproduce it may i have to check my workspace or may be it is not working on openldap but with opendj .

**Comment by aliaksander-samuseu** [comment] 2017-01-13 17:25
@shekhar16 , are you sure all your latest fixes did make to the packages available in repos? May be you should check with Adrian or Yuriy?

**Comment by shekhar16** [comment] 2017-01-22 19:12
The functionality is working fine with openDJ but the issue is with openldap.
issue is fixed on TR and scope page .please check with latest identity build.

**Comment by nynymike** [comment] 2017-02-06 04:38
This is a major usability problem

**Comment by shekhar16** [comment] 2017-02-06 08:56
https://github.com/GluuFederation/oxTrust/issues/457

**Comment by shekhar16** [comment] 2017-02-06 10:49
Fixed. @aliaksander-samuseu please test it with latest build.

**Closed by shekhar16** 2017-02-06 10:49 UTC
Labels: bug
