### ISSUE TITLE
UI session timeout error

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#609] opened 2017-07-07 04:54 UTC
Howto reproduce: 
1. Login to oxTrust & wait for session timeout.
2. Click to any link to protected page.

Old version behaviour: redirecting to login page in oxAuth.
New version behaviour: redirecting to error page with log exception:

2017-07-07 04:43:41,816 ERROR [qtp274064559-16] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:50) - viewId:/authentication/manageCustomAuthentication.htm - View /authentication/manageCustomAuthentication.htm could not be restored.
javax.faces.application.ViewExpiredException: viewId:/authentication/manageCustomAuthentication.htm - View /authentication/manageCustomAuthentication.htm could not be restored.
        at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:212) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:123) [jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) [jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658) [jsf-api-2.2.14.jar:2.2]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.jboss.weld.probe.ProbeFilter$FilterAction.proceed(ProbeFilter.java:329) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.ProbeFilter$FilterAction.proceed(ProbeFilter.java:312) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:173) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.ProbeFilter$FilterAction.doFilter(ProbeFilter.java:338) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.ProbeFilter.embedInfoSnippet(ProbeFilter.java:188) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.ProbeFilter.doFilter(ProbeFilter.java:176) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]

**Comment by yurem** [comment] 2017-08-15 11:34
Duplicate of issue: https://github.com/GluuFederation/oxTrust/issues/626

**Closed by yurem** 2017-08-15 11:34 UTC
Labels: bug
