### ISSUE TITLE
Limit search in SCIM v1

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#322] opened 2016-08-10 12:17 UTC
We have 3 methods in User SCIM v1 where it's possible to get all users:

- [List<GluuCustomPerson> personList = personService.findAllPersons(null);](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim/UserWebService.java#L81)

- [GluuCustomPerson gluuPerson = personService.getPersonByAttribute(searchPattern.getAttribute(), searchPattern.getValue());](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim/UserWebService.java#L437)

- [List<GluuCustomPerson> personList = personService.getPersonsByAttribute(searchPattern.getAttribute(), searchPattern.getValue());](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim/UserWebService.java#L477)

**Comment by uboznikov** [comment] 2016-08-11 05:59
Duplicate of #317

**Closed by uboznikov** 2016-08-11 05:59 UTC
Labels: enhancement
